### ISSUE TITLE
Zooming is animating markers from the corners

### ISSUE THREAD

**Issue by wellguimaraes** [istarkov/google-map-react#510] opened 2018-02-14 01:19 UTC
I checked the [demo app](http://istarkov.github.io/google-map-react/map/main/) and it's behaving the same way when I change zoom. I suppose it's not a feature, right?

**Comment by bzbetty** [comment] 2018-02-14 03:00
also suddenly seeing this behaviour, guessing a Google change causes it?

**Comment by wellguimaraes** [comment] 2018-02-14 03:58
Don't know yet. But tried react-google-maps and it's ok.

**Comment by itsmichaeldiego** [comment] 2018-02-14 07:42
@wellguimaraes You're right, I will to take a look into that soon.

**Comment by jabidof** [comment] 2018-02-14 08:15
Sounds like a google API sudden change in the marker drawing part.

**Comment by goncharov** [comment] 2018-02-14 08:24
New version of api was released https://groups.google.com/forum/#!topic/google-maps-js-api-v3-notify/cp9SiuHXkFc

**Comment by VladimirMilov** [comment] 2018-02-14 11:36
Is there any way to set specific api version?

**Comment by goncharov** [comment] 2018-02-14 11:42
@VladimirMilov try to add `v: '3.30'` into `bootstrapURLKeys`
https://developers.google.com/maps/documentation/javascript/versions

**Comment by mikkelwf** [comment] 2018-02-14 11:44
@goncharov it works locally for me.. 👍

**Comment by VladimirMilov** [comment] 2018-02-14 11:46
It works perfectly man. Thank you! :)

**Comment by jabidof** [comment] 2018-02-14 12:16
Same here. 
Anyone understood what the changes are in the latest GMap API release?

**Comment by Delindel** [comment] 2018-02-14 20:20
Man, i was pulling my hair over this. Adding @goncharov solution works perfectly.

**Comment by danieljodeci** [comment] 2018-02-14 20:32
I tried adding to my bootstrapURLKeys like so:

`bootstrapURLKeys={{key: GOOGLE_MAPS_API_KEY, v: '3.30'}}`

and still getting the same marker animation from the top left. Also my child markers don't register click events.

**Comment by RoelanddeBetue** [comment] 2018-02-15 13:12
If i change to version 3.30 or 3.31 the markers keep having a lag in animation when it pans or zooms

**Comment by mikeriley131** [comment] 2018-02-15 17:31
We rolled back to 3.29 and all is working properly again.

`https://maps.googleapis.com/maps/api/js?key=%REACT_APP_GOOGLE_MAP_API_KEY%&libraries=places&v=3.29`

**Comment by itsmichaeldiego** [comment] 2018-02-16 20:23
Good work guys! How do you guys feel about changing our default version to this one that works?

**Comment by goncharov** [comment] 2018-02-17 08:15
@mikeriley131 Cool, but 3.29 is not provided anymore. It’s 3.30

**Comment by mikeriley131** [comment] 2018-02-17 21:00
@goncharov Works just fine in our production environment. We just get a console warning saying is's a retired version: `Google Maps API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version`

<img width="552" alt="screen shot 2018-02-17 at 1 57 59 pm" src="https://user-images.githubusercontent.com/5115726/36345583-dc4d1646-13ea-11e8-8816-a99b65acb32c.png">

**Comment by jeffodle** [comment] 2018-02-18 11:11
Thanks guys. This was making me insane.

**Comment by istarkov** [comment] 2018-02-18 11:40
It seems like `scale` transform is no longer applied by google on a layers on zooming.
So markers should be re-rendered in `draw` method and not on `idle`.

May be this code ```          if (this_.markersDispatcher_) {
            this_.markersDispatcher_.emit('kON_CHANGE')``` from 'idle' moved into `draw` should help. I'm not sure.

**Comment by kpennell** [comment] 2018-02-22 22:50
@goncharov @istarkov where to add the new version? 

How do I add this exactly?
> try to add v: '3.30' into bootstrapURLKeys

**Comment by itsmichaeldiego** [comment] 2018-02-23 19:15
@kpennell What do you mean? 🤔

**Comment by kpennell** [comment] 2018-02-23 21:18
@itsmichaeldiego Was trying to help noobies who didn't understand where to put v:'3.30'

**Comment by BrodaNoel** [comment] 2018-02-25 18:59
Fixed with `v: '3.30'`

**Comment by itsmichaeldiego** [comment] 2018-02-26 19:55
Oh thanks @kpennell I thought you said you were stuck there!

**Comment by alexmcmillan** [comment] 2018-02-27 08:55
I tried @istarkov's suggestion, moving the `kON_CHANGE` emit from idle to draw, no luck :(

This is a right PITA.  The new API has such sweet, smooth zooming.

**Comment by istarkov** [comment] 2018-02-27 09:00
@alexmcmillan just calling onchane is not enough, all that stuff with recalculating internals before like his_._onBoundsChanged(map, maps); are also needed?

**Comment by alexmcmillan** [comment] 2018-02-27 09:10
Yeah I thought I was being a bit optimistic... 

Just for giggles, I dumped the entirety of `idle` inline into `draw`... no change.

**Comment by istarkov** [comment] 2018-02-27 09:13
So inside draw this https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L998 return same result as it was?

**Comment by alexmcmillan** [comment] 2018-02-27 09:27
Exactly the same.

I dumped some logs in draw/idle, as well as dumping the center lat/lng immediately after the line you referenced, then triggered a single zoom "step".  `draw` executed about 20 times, `idle` once... all with identical values.

**Comment by istarkov** [comment] 2018-02-27 09:34
As I see google examples on their site with overlays are working good, so for some reason transforms are not broken there. It will be interesting whats changed there (if changed)

**Comment by jurgenzz** [comment] 2018-02-27 13:13
rolling back fixes transform issue, but breaks "draggable" parameter. 

For instance, when clicking on child and disabling map dragging, this breaks v3.30, but works with newer ones. And the other way around with transforming.

**Comment by stephenfarrar** [comment] 2018-03-02 05:17
Thanks for looking at this issue.

I left some detailed advice, and a link to a code sample in #490 , which I'm not sure whether people have seen. So I'm just drawing attention to it again.

**Comment by stephenfarrar** [comment] 2018-03-03 12:57
I've managed some hacks that make things sort-of work.

In `google_map.js`
* Delete the `zoom_changed` listener entirely.
* After `panes.overlayMouseTarget.appendChild(div);` add the line
  ```_this.geoService_.setProjection(overlay.getProjection());```
* In the `draw()` method, comment out the lines that set `div.style.left` and `.top`.

In `utils/geo.js`
* Add a `setProjection()` method that saves the argument as `this.projection_`
* The `project()` method gets these lines:
  ```
  if (this.projection_) {
    if (viewFromLeftTop) {
      return this.projection_.fromLatLngToContainerPixel(
          {lat: () => ptLatLng.lat, lng: () => ptLatLng.lng});
    } else {
      return this.projection_.fromLatLngToDivPixel(
          {lat: () => ptLatLng.lat, lng: () => ptLatLng.lng});
    }
  }
  ```
* Apply similar treatment to `unproject()` but with `this.projection_.fromDivPixelToLatLng(ptXY).toJSON()` and so on. 

This probably breaks a lot of other things in the process. But the markers do animate properly when zooming and panning.

I hope someone else will be able to start from here and turn this into something that works.

**Comment by itsmichaeldiego** [comment] 2018-03-10 21:28
@wellguimaraes @bzbetty @jabidof @goncharov @vladimirmimlov @mikkelwf @Delindel @RoelanddeBetue @mikeriley131 @jeffodle @kpennell @BrodaNoel @alexmcmillan @istarkov @jurgenzz @stephenfarrar:

I am handling this in #530, so by default we don't have to set the version `3.30` or `3.31`, the problem is that the `3.32` version is experimental and causing us bugs. When this version gets stable we should test it to see if this is still an issue. More details in [PR #530 description](https://github.com/istarkov/google-map-react/pull/530#issue-174187310)

**Closed** 2018-03-10 21:57 UTC

**Comment by kpennell** [comment] 2018-03-30 17:02
@itsmichaeldiego Darn. This came back for me. Using .34
