### ISSUE TITLE
Get map instance

### ISSUE THREAD

**Issue by lovegroveandy** [istarkov/google-map-react#19] opened 2015-07-17 03:26 UTC
Hi I was trying to work out a way of triggering a resize of the map along the lines of google.maps.event.trigger(map, "resize"); Clearly to do this I would need the map instance. Do you have any ideas at all?

Many thanks for a great library.

**Comment by istarkov** [comment] 2015-07-17 05:46
Why do you need to trigger resize?

**Comment by lovegroveandy** [comment] 2015-07-17 05:51
Thanks for the prompt reply. 

I have a map component which is rendered once as a thumbnail on the main page with a link which shows a modal window with another instance of the map in a larger format. The modal map is rendering but no map panels are visible until I resize the viewport for some reason. I just figured the easiest solution would be to trigger a resize event on that instance when the modal shows.

**Comment by istarkov** [comment] 2015-07-17 06:03
Look's like at the moment of GoogleMap control created, modal has no size (width,height=0) or/and not displayed, the simple solution is to add something like this in render
```
render() {
  return this.props.modalIsOpen ? <GoogleMap /> : null
}
```

**Comment by canvaskisa** [comment] 2015-08-22 14:56
Hey, i have a similar question. I want to place overlay with an image on map, but i have no idea how to get map instance and i don't know other options about how to do that.

**Comment by istarkov** [comment] 2015-08-22 17:50
As i wrote here https://github.com/istarkov/google-map-react/issues/5#issuecomment-111847899 
(*i have no plans to expose google map api in any way.*)
because of this https://github.com/istarkov/google-map-react/issues/3#issuecomment-111237765

**Comment by istarkov** [comment] 2015-10-03 21:11
Closed as duplicate of this
https://github.com/istarkov/google-map-react/issues/43

**Closed by istarkov** 2015-10-03 21:11 UTC
