### ISSUE TITLE
Is there a way to access the Geocoder?

### ISSUE THREAD

**Issue by dgcoffman** [istarkov/google-map-react#32] opened 2015-09-02 00:01 UTC
I need to center on an address, not a lat/long.

**Comment by jedwards1211** [comment] 2015-09-03 20:08
`google-map-react` uses `window.google.maps` if it's already available; it only automatically loads it if it's not already present.
So you can load the Google Maps API yourself before the `google-map-react` bundle (via script tag in the header or whatever) and use the Geocoder in it.  It's also possible to use the Geocoding Service via pure REST requests without loading any library.

**Comment by jedwards1211** [comment] 2015-09-11 05:04
Let me know if this answers your question and I'll close it

**Comment by istarkov** [comment] 2015-10-03 21:10
Closed as duplicate of this
https://github.com/istarkov/google-map-react/issues/43

**Closed by istarkov** 2015-10-03 21:10 UTC

**Comment by rojobuffalo** [comment] 2016-11-19 03:34
Just for clarification, is there not a way to do a reverse geocode lookup entirely with this package? Is that considered out of scope?

**Comment by AntoniusGolly** [comment] 2018-01-24 12:04
@rojobuffalo In my opinion this is out of scope. Geocoding and drawing maps are two different things, not only in this react wrapper but also in the Google Maps Api. With the native api you can't plot a map for a given address directly. And this is for a good reason: not every address (query string) results in **one** Lat/Lon response. And it is up to your application how you deal with multiple results.

**Comment by itsmichaeldiego** [comment] 2018-01-24 22:55
@rojobuffalo I don't think geocode lookup is scoped for this package really. We try to keep this package simple as well, and if you want to do something different you can always do it out of the box with the google maps api.

**Comment by Bernabe-Felix** [comment] 2018-02-03 04:40
In case somebody needs it:
```
<GoogleMapReact
{...otherOptions}
 onGoogleApiLoaded={initGeocoder}
>
 <AnyReactComponent {...props} />
<GoogleMapReact>

initGeocoder = ({ _, maps }) => {
  const Geocoder = new maps.Geocoder();
};
```

**Comment by itsmichaeldiego** [comment] 2018-02-06 01:03
@Bernabe-Felix Exactly what I was mentioning, thanks for sharing that! We can use anything from maps api using `onGoogleApiLoaded`

**Comment by terrabl** [comment] 2018-02-13 22:10
@Bernabe-Felix I wasn't able to get this to work in my code, it keeps saying that "InitGeocoder" is not defined.

**Comment by BernabeFelix** [comment] 2018-02-13 22:35
did you try `this.initGeocoder`?

**Comment by itsmichaeldiego** [comment] 2018-02-14 01:11
@terrabl Depending on your structure you might need to do:

```
const initGeocoder = ({ maps }) => {
  const Geocoder = new maps.Geocoder();
};
```

**Comment by kaycebasques** [comment] 2018-05-15 03:14
FYI when I do something like:

```
const initGeocoder = ({ maps }) => {
  console.log(maps);
};
```

I get an error from Google saying that it's dangerous to use internal APIs.

**Comment by itsmichaeldiego** [comment] 2018-05-15 03:37
@kaycebasques Because you need to add `yesIWantToUseGoogleMapApiInternals`.

```
  <GoogleMapReact
    zoom={props.zoom}
    center={props.center}
    bootstrapURLKeys={{
      key: process.env.MAP_KEY,
      language: 'en',
    }}
    yesIWantToUseGoogleMapApiInternals
  >
    {props.children}
  </GoogleMapReact>
```

**Comment by kaycebasques** [comment] 2018-05-15 03:39
Except I don't want to use API internals ;) Google is explicitly warning against it.

I think I got a solution working pretty easily with the [Google Maps Node.js client](https://www.npmjs.com/package/@google/maps).

```
...
import client from '@google/maps';

class Pickup extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      client: client.createClient({key:"YOUR_KEY_HERE"})
    };
    this.state.client.geocode({ address: '1600 Amphitheatre Pkwy, Mountain View'},
      (error, response) => console.log(response.json.results));
  }
}
...
```

My code is probably terribly unidiomatic... I'm a React newbie... but you get the idea.

**Comment by ratonjuancarlos** [comment] 2018-09-05 19:10
Hi! 
I think I missed in some place.
How works this `initGeocoder` to use the addres in the child component that I want to render?
This is my code, if it clearify my point:
```javascript
const stores: [
    {
      address: "Florida 533, caba, argentina",
      id: 1,
    },
    {
      address: "Maipu 233, caba, argentina",
      id: 2,
    }]
```
```javascript
      <GoogleMapReact
          onGoogleApiLoaded={initGeocoder}
          yesIWantToUseGoogleMapApiInternals
        >
          /*
           * I want to render 2 or more *stores*
           */
          {
           stores.map(sucursal => 
              <MarkerComponent
                address={sucursal.address} // this is the data that I have
              />
            );
         }
        </GoogleMapReact>
```


I can render 2 or more stores if I use `lat` and `lng`, but I only have `address`.
How the `onGoogleApiLoaded` or the `initGeocoder` will help me?
Thanks!!!
