### ISSUE TITLE
onIdle callback [feature request]

### ISSUE THREAD

**Issue by raulmatei** [istarkov/google-map-react#42] opened 2015-10-01 09:32 UTC
Hi,

Is it possible to add an `onIdle` callback, that will get `this.map_` `this.maps_` as arguments - it will be easier for those who want to work with the map instance and not only:

```JS
this.props.onIdle(this.map_, this.maps_);
```

I used to work with the map instance to enable some functionality that's not implemented in this component, and I had to create a loop to make sure I'll always get it.

Thanks,
Raul.

**Comment by istarkov** [comment] 2015-10-03 21:10
Closed as duplicate of this
https://github.com/istarkov/google-map-react/issues/43

**Closed by istarkov** 2015-10-03 21:10 UTC
