### ISSUE TITLE
Support Touch Events for markers

### ISSUE THREAD

**Issue by sai-prasanna** [istarkov/google-map-react#82] opened 2016-01-07 06:48 UTC
Currently mouse events are supported for markers using onChildMouseDown, etc. Is it possible to support tap events? I want to contribute, want to know where to add tap event handlers

**Comment by istarkov** [comment] 2016-01-13 15:16
Can't say much about touch events

**Comment by istarkov** [comment] 2016-01-13 15:18
Close as a duplicate of this https://github.com/istarkov/google-map-react/issues/28

**Closed by istarkov** 2016-01-13 15:18 UTC
