### ISSUE TITLE
Update to @mapbox/point-geometry

### ISSUE THREAD

**Issue by eelfonik** [istarkov/google-map-react#445] opened 2017-09-25 08:31 UTC
Hello, thanks for the great lib.
I recently got a warning saying:
`WARN deprecated point-geometry@0.0.0: This module has moved: please install @mapbox/point-geometry instead`.

Do you have a plan to upgrade to the latest version? If I got it right, we have only used that in `src/utils/lib_geo/transform.js` to create point geometry, and it doesn't change API or anything. 

Thanks!

**Comment by quiqueg** [comment] 2017-11-17 13:16
Duplicate of #382

**Comment by itsmichaeldiego** [comment] 2017-12-20 20:57
Duplicate of #382

**Closed by itsmichaeldiego** 2017-12-20 20:57 UTC
