### ISSUE TITLE
Support Relay components as markers

### ISSUE THREAD

**Issue by mattecapu** [istarkov/google-map-react#150] opened 2016-05-04 07:09 UTC
Using components which uses Relay currently doesn't work because the `relay` property isn't passed down when markers are drawn.
I'd like to make a PR for this but I don't really know how the library works. If @istarkov could give some advice on where to look it'd be great.

**Comment by mattecapu** [comment] 2016-05-04 07:24
Maybe [here](https://github.com/istarkov/google-map-react/blob/master/src/google_map_markers.js#L255)?

**Comment by istarkov** [comment] 2016-05-04 11:39
IMHO the problem is the same as here https://github.com/istarkov/google-map-react/issues/64,
As I have no idea how to pass all context into other rendering tree.
So the problem is here https://github.com/istarkov/google-map-react/blob/master/src/google_map.js#L414

Have you tried to pass relay variables explicitly? As like as `<Marker relay={relay}` ?

**Comment by mattecapu** [comment] 2016-05-05 06:21
Passing `relay` as a prop doesn't work, however passing the current `RelayEnvironment` as context _seems_ to work.
When I render the component as-is I get these errors:
> warning.js:44 Warning: Failed Context Types: Invalid prop/context `relay` supplied to `Relay(MapMarker)`, expected `undefined` to be an object conforming to the `RelayEnvironment` interface. Check the render method of `MapExplorer`

> warning.js:44 Warning: Failed Context Types: Required context `route` was not specified in `Relay(MapMarker)`. Check the render method of `MapExplorer`

> invariant.js:38 Uncaught Invariant Violation: RelayContainer: `Relay(MapMarker)` was rendered with invalid Relay context `undefined`. Make sure the `relay` property on the React context conforms to the `RelayEnvironment` interface

If I add this to the Map component
```js
static childContextTypes = {
    relay: React.PropTypes.any
};
getChildContext() {
    return { relay: RelayCommonEnvironment.get() };
}
```
The errors disappear, but data isn't actually passed downstream (this.props.&lt;fragmentName&gt; on MapMarker is `undefined`).
`RelayCommonEnvironment.get()` returns the environment Relay was initialized with.

This is how the components are rendered
```js
render() {
    const { markers } = this.props.mapExplorer;
    const comps = markers.map((marker, index) =>
        <MapMarker
            key={index}
            markerFragment={marker}
            lat={marker.location.lat} lng={marker.location.lng}
        />
    );

    return (
        <GoogleMap {...mapSettings}>
            {comps}
        </GoogleMap>
    );
}
```
(`marker` is not `undefined` when I assign it to `markerFragment`, so the value is changed by Relay somewhere between the creation and the rendering)

**Comment by istarkov** [comment] 2016-05-10 19:42
At now I have no idea how to pass all context vars into other rendering tree. Help wanted as in related issue. Ill close this issue as its the same problem as there.

**Closed by istarkov** 2016-05-10 19:42 UTC

**Comment by mattecapu** [comment] 2016-05-17 09:10
**Good news everyone! I think I solved the issue** :tada: :tada:

Just follow the [documentation](https://facebook.github.io/react/docs/context.html).

1. First, explicitly requiring context to be accessible in the component which renders `GoogleMap`
```js
class MapComponent extends React.Component {

    // This way
    static contextTypes = {
        router: React.PropTypes.object.isRequired,
        relay: React.PropTypes.object.isRequired
    };

    //...
}
```
2. Generate a new context in the rendering tree of each Marker. I find useful to use a HoC to do that, but you could do it in the component itself (moreover, this is probably not the best way to write an HoC)
```js
class WithContext extends React.Component {
    // capture the fields passed by MapComponent
    static childContextTypes = {
        router: React.PropTypes.object.isRequired,
        relay: React.PropTypes.object.isRequired
    };

    // provide the context to children
    getChildContext() {
        return {
            router: this.props.context.router,
            relay: this.props.context.relay
        };
    }

    render() {
        const Component = this.props.component
        return <Component {...this.props} />;
    }
}
```

3. Pass your context from `Map`'s `render()` method
```js
render() {
    const markers = collection.map((item, index) =>
        <WithContext
            component={MapMarker}
            context={this.context}
            props_of_MapMarker={item}
            key={index}
            {...location}
        />
    );

    return (
        <GoogleMap {...mapOptions}>
            {markers}
        </GoogleMap>
    );
}
```

4. Enjoy! :tada:

@istarkov probably this strategy could be merged in the library, what do you think?

**Comment by istarkov** [comment] 2016-07-20 13:52
Should work without any hacks after this pr https://github.com/istarkov/google-map-react/pull/198
Now in 0.16v
