### ISSUE TITLE
Plans to add direction-service support?

### ISSUE THREAD

**Issue by sslash** [istarkov/google-map-react#5] opened 2015-06-12 16:28 UTC
Totally dig this package. However, in order for my team to use this, we need google direction-service to get distances between places. Do you have plans to add this into your google-maps abstraction?

**Comment by istarkov** [comment] 2015-06-12 16:47
To get distances or to draw distances like here https://developers.google.com/maps/documentation/javascript/examples/directions-travel-modes ?

**Comment by sslash** [comment] 2015-06-12 18:23
Yes!

**Comment by istarkov** [comment] 2015-06-12 18:28
Yes draw or yes just measure distance? :-)

**Comment by sslash** [comment] 2015-06-12 18:32
I actually need both. But deffs drawing!

**Comment by istarkov** [comment] 2015-06-14 16:36
I think about, and it looks like my nearest plans are.
* add canvas (webgl, svg) to allow custom overlays
(*this allows you to draw directions but not in an easy way*).

And i have no plans to expose google map api in [any way](https://github.com/istarkov/google-map-react/issues/3#issuecomment-111237765). (May be geo only)

There is a great react library https://github.com/tomchentw/react-google-maps with almost full google api support, and it could be more easy and correct to merge this library into @tomchentw library (if he allows), than add api here.

**Comment by sslash** [comment] 2015-06-16 15:57
I see. Anyhow, it would be great with these features in this lib, as I prefer it more then other libs I've seen :)

**Comment by istarkov** [comment] 2015-10-03 21:11
Closed as duplicate of this
https://github.com/istarkov/google-map-react/issues/43

**Closed by istarkov** 2015-10-03 21:11 UTC
Labels: question
