### ISSUE TITLE
Conditional marker rendering

### ISSUE THREAD

**Issue by kjeske** [istarkov/google-map-react#187] opened 2016-07-03 11:44 UTC
When we try to use conditional rendering like:
```
<GoogleMap ...>
  {showMyMarker && <MyMarker lat={lat} lng={lng} />}
</GoogleMap>
```

the following exception will be thrown:
`TypeError: Cannot read property 'props' of null`

I suppose the problem is that the GoogleMap component assumes that all the children are valid react components, so when one of the child is null (as in the example) the error is shown.

**Comment by istarkov** [comment] 2016-07-03 11:47
Duplicate of https://github.com/istarkov/google-map-react/issues/164

**Comment by kjeske** [comment] 2016-07-03 11:55
For interested, the following approach works:
```
<GoogleMap ...>
  {showMyMarker ? <MyMarker lat={lat} lng={lng} /> : []}
</GoogleMap>
```

**Comment by istarkov** [comment] 2016-07-03 12:13
`null`, `undefined` also will work

**Closed** 2016-07-03 12:14 UTC

**Comment by kjeske** [comment] 2016-07-03 12:28
My current solution:
```
const marker = (result) => result || []
```
```
<GoogleMap ...>
  {marker(showMyMarker && <MyMarker lat={lat} lng={lng} />)}
</GoogleMap>
```
IMO it looks more clean now.

BTW null doesn't work for me. It shows the same error. I saw your example, but in my code it doesn't work. I will stay with empty array :)
