### ISSUE TITLE
Conditionally rendering marker

### ISSUE THREAD

**Issue by shark0der** [istarkov/google-map-react#203] opened 2016-07-24 18:24 UTC
I have the following code, in which I am trying to conditionally render a marker:
```
        <GoogleMap>
        {
          userLocation
          ? <UserMarker key="user" {...userLocation} />
          : null
        }
        </GoogleMap>
```

However I'm getting the following error:
```
Uncaught TypeError: Cannot read property 'props' of null
google_map_markers.js:244
```

The code triggering the error seems to be this:

![image](https://cloud.githubusercontent.com/assets/528959/17085583/d0c9b9e2-51e4-11e6-8b08-78392d208ea6.png)

As react allows passing null children I think it would be appropriate to check if the child is null.

**Comment by istarkov** [comment] 2016-07-24 18:36
duplicate of #164
It works with `null` https://jsbin.com/munokamuhe/edit?js,console,output
please provide jsbin with non working null

**Comment by shark0der** [comment] 2016-07-24 19:06
Here: https://jsbin.com/vajivuzehu/1/edit?js,console,output

**Comment by istarkov** [comment] 2016-07-24 19:25
Looks like React way just to skip all falsee value child without any errors.
So what is better - to throw/warn if child value is false, or just skip it as React do.
I'll accept a PR with any solution.

**Comment by shark0der** [comment] 2016-07-24 21:40
I've returned `null` if `child` is falsy. The resulting array is passed to react so no need to filter out them after map.

**Closed** 2016-07-24 22:20 UTC
