### ISSUE TITLE
TypeError: Cannot read property 'clientWidth' of null

### ISSUE THREAD

**Issue by antonovm** [istarkov/google-map-react#104] opened 2016-02-09 16:04 UTC
Hi, I get the following error in console:

> google_map.js:534 Uncaught TypeError: Cannot read property 'clientWidth' of null

I comes from this function:

```
    this._setViewSize = function () {
      var mapDom = ReactDOM.findDOMNode(_this.refs.google_map_dom);
      _this.geoService_.setViewSize(mapDom.clientWidth, mapDom.clientHeight);
      _this._onBoundsChanged();
    };
```

Everything works ok, but this error is just bothering. Is there something I do wrong? Thanks!

**Comment by istarkov** [comment] 2016-02-09 18:21
please provide short example on jsbin (as like as in ecamples) or share your code

**Comment by antonovm** [comment] 2016-02-09 19:41
Couldn't get it on jsbin. It's a very simple code. I try to make it isomorphic though but the error shows on client:

 ```
 render() {
    const timeslots = this.props.timeslots;
    const markers = Object.keys(timeslots).map((id) => {
      return <MapMarker key={id} lat={this.props.places[timeslots[id].place].latitude} lng={this.props.places[timeslots[id].place].longitude} timeslot = {timeslots[id]} />;
    });
    return (
        <GoogleMap
            defaultCenter={this.props.center}
            defaultZoom={this.props.zoom} >
          {markers}
        </GoogleMap>
    );
  }
```

**Comment by istarkov** [comment] 2016-02-09 20:07
Without real example I can't say much. 
this call https://github.com/istarkov/google-map-react/blob/a6e6b37675a59d5baad38af5bddcecf8afcee076/src/google_map.js#L653
can return null iif _initMap has called before didMount, or component has unmounted in a small interval.

So try to find the minimal example. 

As an example I lost 8 hours to find a minimal example for this https://github.com/facebook/react/issues/5719 (Yes React also contains bugs)

**Comment by antonovm** [comment] 2016-02-09 20:30
Ok will try to, thanks!

**Comment by antonovm** [comment] 2016-02-13 23:51
I'm quite sure it has something to do with Redux DevTools https://github.com/gaearon/redux-devtools 
When I switch it off, error disappears.

**Comment by gabriel-laet** [comment] 2016-03-17 21:17
We've been using `google-map-react` in production and this error happens frequently. I didn't have time to fix it, but apparently the error is caused when your DOM node is not found. We usually see this error when user changes from one page to another (when map is removed).

Here is the stack trace we have from Sentry:
![google-map-react-stack-trace](https://cloud.githubusercontent.com/assets/73142/13861493/5cf49470-ec6c-11e5-819f-89645f9db4d7.png)

**Comment by istarkov** [comment] 2016-03-17 21:35
I know how to reproduce this "bug", 
you need to rerender MapHolder after first render, and remove Map on rerendering step.
So at the moment this._setViewSize(); called, component is unmounted.

Yes it is a bug, but IMHO it shows that something wrong in your app. What the need of one moment rendering-unrendering steps.

The other idea, that bug is not because of logic above. Have you this bug in your app now? Can you share app to play with.

**Comment by antonovm** [comment] 2016-03-17 21:42
As for me, I used https://github.com/erikras/react-redux-universal-hot-example as a base for my app, it had the following issue: https://github.com/erikras/react-redux-universal-hot-example/pull/961

**Comment by istarkov** [comment] 2016-03-17 21:53
should be fixed by #119 
at npm as 0.11.1

**Comment by istarkov** [comment] 2016-03-17 21:58
please write if it helps.

**Comment by gabriel-laet** [comment] 2016-03-17 21:58
@istarkov awesome!

**Closed** 2016-07-21 19:08 UTC
Labels: bug
